apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: omed-envs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - brand: omed-prod
          - brand: omed-staging
  template:
    # kind: Application
    metadata:
      name: "{{.brand}}"
      namespace: default
    spec:
      project: default
      source:
        repoURL: https://github.com/jabczyk/przychodnia-pk.git
        targetRevision: HEAD
        path: "k8s/omed/overlays/{{.brand}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: omed-envs
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
