apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.host
    targets:
      - select:
          kind: Ingress
          name: ingress
        fieldPaths:
          - spec.rules.0.host
